#!/bin/bash

## This docker image includes a copy of Dyalog APL that should only be used within this container to run the Tatin server application and must not be extracted.

## This file replaces the Dyalog mapl script

export DYALOG=/opt/mdyalog/{{DYALOG_RELEASE}}/64/unicode/
export LD_LIBRARY_PATH="${DYALOG}:${LD_LIBRARY_PATH}"
export TERM=dumb
export APL_TEXTINAPLCORE=${APL_TEXTINAPLCORE-1}
export TRACE_ON_ERROR=0
export SESSION_FILE="${SESSION_FILE-$DYALOG/default.dse}"

export CLASSICMODE=1 
export SINGLETRACE=1

WS="/app/Server/Server.dws"

#if [ -n "${RIDE_INIT}" ]; then
#    $DYALOG/dyalog.rt +s -q ${WS} $@
#else
#    $DYALOG/dyalog.rt -s ${WS} $@
#fi

$DYALOG/dyalog.rt +s -q ${WS} $@
