[project]

site_name = "Tatin User Guide"
site_description = "Tatin is a package manager for Dyalog APL."
site_author = "aplteam"
site_url = "https://5jt.github.io/Tatin/"

repo_url = "https://github.com/aplteam/Tatin"
repo_name = "aplteam/Tatin"

docs_dir = "source"

nav = [
  { "Home" = [
    { "About Tatin" = "index.md" },
    { "Load and update strategy" = "load-and-update-strategy.md" },
    { "Glossary" = "glossary.md" },
    { "Release notes" = "release-notes.md" },
    { "Previous version" = "https://tatin.dev/v1/documentation" },
  ] },
  { "Use" = [
    { "Get started" = "get-started.md" },
    { "User commands" = "user-commands.md" },
    { "API functions" = "api.md" },
    { "Settings" = "user-settings.md" },
    { "Older versions" = "older-versions.md" },
  ] },
  { "Publish" = [
    { "About publishing" = "publish.md" },
    { "Publish packages" = "publish-packages.md" },
    { "User commands" = "user-commands-publish.md" },
    { "Package configuration" = "package-configuration.md" },
    { "Public interface" = "public-interface.md" },
  ] },
  { "Host" = [
    { "About hosting" = "host.md" },
    { "Install" = "install-server.md" },
    { "Security" = "secure-server.md" },
    { "Maintenance" = "maintenance.md" },
    { "User commands" = "user-commands-host.md" },
  ] },
  { "Contribute" = [
    { "About contributing" = "contribute.md" },
    { "Develop" = "develop.md" },
    { "Test" = "test.md" },
    { "Create a new version" = "create-version.md" },
    { "Github" = "github.md" },
  ] },
]

extra_css = [
  "style/main.css",
  "style/extra.css",
  "style/admonition-ucmdhelp.css",
]

extra_javascript = [
  "javascripts/mathjax.js",
  "https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6",
  "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]

[project.theme]

variant = "classic"
custom_dir = "overrides"
favicon = "img/favicon.ico"
logo = "img/tatin-logo.svg"

features = [
  "content.tabs.link",
  "navigation.instant",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tracking",
]

[project.theme.font]
text = "Be Vietnam Pro"

[[project.theme.palette]]
scheme = "default"
primary = "custom"
accent = "custom"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.markdown_tables_extended]
[project.markdown_extensions.sane_lists]

[project.markdown_extensions.toc]
title = "On this page"
permalink = true

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tilde]

[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
options = { custom_icons = ["overrides/.icons"] }

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
